### ISSUE TITLE
Latest builds do not have zlib enabled

### ISSUE THREAD

**Issue by kcajf** [conda-forge/boost-cpp-feedstock#122]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The latest builds do not have zlib enabled.
For example https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/489010/logs/27
shows zlib: no.
The linux-64/boost-cpp-1.77.0-he72f1d9_2.tar.bz2 build published 10 days ago is broken, whereas the linux-64/boost-cpp-1.77.0-h359cf19_1.tar.bz2 build published many months earlier is OK.

It appears that the previous fix for this, https://github.com/conda-forge/boost-cpp-feedstock/issues/114 & https://github.com/conda-forge/boost-cpp-feedstock/pull/115 by @benmwebb, was not actually merged into `main` - it was just merged into a version branch.

### Installed packages

```shell
conda list
```

### Environment info

```shell
conda info
```

**Comment by jakirkham** [comment]
Thanks for raising! If this is a simple cherry-pick, would you like to submit a PR cherry-picking that change to `main`?

**Comment by benmwebb** [comment]
@kcajf: you're correct - my PR in #115 specifically fixed this (and added a test to make sure it stays fixed!) for the 1.74.x branch. It would certainly make sense to apply the same fix to main. It should apply fairly cleanly, but if you're not comfortable taking this on, let me know and I can make a new PR.

**Comment by kcajf** [comment]
Thanks. Yes please, could you make a PR?

**Comment by jakirkham** [comment]
Fix is merged! Thanks Ben for working on that 🙏

New packages should build and upload shortly. Note that even after the packages are up it takes a bit of time for them to mirror to CDN before they are generally available.

**Comment by kcajf** [comment]
Thanks both!
