### ISSUE TITLE
Drop MPI headers

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/boost-cpp-feedstock#131]
Currently the MPI headers are getting packaged in `boost-cpp`. However these should be in `libboost-mpi` ( https://github.com/conda-forge/libboost-mpi-feedstock/issues/9 ). These should be dropped from `boost-cpp` and `libboost-mpi` rebuilt.

**Comment by sdebionne** [comment]
The two packages are tightly coupled anyway, `libboost-mpi` cannot be installed without `boost-cpp`, so I am not sur if this a real issue...
To me, `libboost-mpi` is a kind of subpackage that introduces variants for each MPI flavors, variants that we don't want to deal with in the main package.

**Comment by jakirkham** [comment]
Yeah just thinking about this from a separation of concerns perspective. Namely should `libboost-mpi` contain all MPI components (including headers)?

In any event, if this change were to be made, it would probably make more sense to do as part of a version upgrade instead of on its own

**Comment by sdebionne** [comment]
With the boost unification effort, I guess this can be safely closed?

**Comment by h-vetinari** [comment]
I had a look at the situation and wrote [down](https://github.com/conda-forge/boost-feedstock/pull/164#issuecomment-1690778916) what I found. I think it can indeed be closed.
