### ISSUE TITLE
Incompatibility between boost 1.78.0 and libcxx 16

### ISSUE THREAD

**Issue by traversaro** [conda-forge/boost-cpp-feedstock#134]
### Comment:

boost 1.78.0 is not compatible with libcxx 16 that was recently released in conda-forge (https://github.com/conda-forge/libcxx-feedstock/pull/113). A fix  was released in boost 1.81 (https://github.com/boostorg/config/pull/440), but boost 1.78.0 is the version pinned in conda-forge. I tought backporting the fix in 1.78.0, but from https://github.com/conda-forge/boost-cpp-feedstock/pull/130 it seems that due to ABI breakage we cannot backport stuff to 1.78.0 .

fyi @conda-forge/boost-cpp 

Related issues:
* https://github.com/conda-forge/libcxx-feedstock/issues/114
* https://github.com/robotology/robotology-superbuild/issues/1375

**Comment by FlorianDubath** [comment]
Any workaround? Is it possible to specify the libcxx version?

**Comment by traversaro** [comment]
Sure, possible workaround are:
* Define `_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY` in your code if you are using libcxx 16 (that is basically what the boost fix in https://github.com/boostorg/config/pull/440 actually does)
* Pin libcxx to <16, i.e. `mamba install "libcxx<16".

**Comment by FlorianDubath** [comment]
On Azure DevOps libcxx<16 is used to create the ## Package Plan ##
 but then the environment is reloaded and libcxx:16.0.0-h71dddab_0 re-installed...

**Comment by traversaro** [comment]
> On Azure DevOps libcxx<16 is used to create the ## Package Plan ## but then the environment is reloaded and libcxx:16.0.0-h71dddab_0 re-installed...

I am not sure to which specific case are you referring to, if you link or provide more details it is easier to help you.

**Comment by FlorianDubath** [comment]
> I am not sure to which specific case are you referring to, if you link or provide more details it is easier to help you.

Sure: I have a feedstock configured to be use with $conda smithy rerender  which reciepe/meta.ymel requierment part is (with the libcc requierment added):
`requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
    host:
        - python
        - libcxx<16
        - boost 
        - elements ==6.1.2
        - cfitsio >=3.470
        - CCfits >=2.5
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cfitsio', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('CCfits', min_pin='x.x', max_pin='x.x') }}
`

in the pipeline runs for osx (linux is going smoothly) I got a list of package to be installed which contains 
`
 boost:           1.78.0-py39h6dc771e_4     conda-forge
 boost-cpp:       1.78.0-h8b082ac_1         conda-forge
 libcxx:          15.0.7-h71dddab_0         conda-forge
`

then after executing the transaction if specify again  "The following NEW packages will be INSTALLED:" and this time appears:
`
libcxx:             16.0.0-h71dddab_0         conda-forge
`
and of course the build failed due to 
`#include <boost/program_options.hpp>`

**Comment by FlorianDubath** [comment]
I have tried to define _LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY

The build command is: 
`$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++ -DBOOST_FILESYSTEM_VERSION=3 -DELEMENTS_DEFAULT_LOGLEVEL=DEBUG -DNDEBUG -D_GNU_SOURCE -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY -Df2cFortran -I$SRC_DIR/build/AlexandriaKernel -I$SRC_DIR/AlexandriaKernel -I$SRC_DIR/build/include -I$SRC_DIR -isystem /opt/local/include/llvm140/c++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/alexandria-2.28.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -std=c++17 -stdlib=libc++ -Wno-deprecated -Wno-overloaded-virtual -Wno-char-subscripts -Wno-unused-parameter -Qunused-arguments -O3 -DNDEBUG -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -MD -MT AlexandriaKernel/CMakeFiles/AlexandriaVersion.dir/src/program/AlexandriaVersion.cpp.o -MF CMakeFiles/AlexandriaVersion.dir/src/program/AlexandriaVersion.cpp.o.d -o CMakeFiles/AlexandriaVersion.dir/src/program/AlexandriaVersion.cpp.o -c $SRC_DIR/AlexandriaKernel/src/program/AlexandriaVersion.cpp`

but I got the same crash

**Comment by traversaro** [comment]
> then after executing the transaction

Which transactions? Probably you also need to add "libcxx<16" there?

**Comment by FlorianDubath** [comment]
OK eventually I got it working: the key put in everywhere:
`requirements:
    build:
        (...) 
        - libcxx<16
    host:
        (...)
        - libcxx<16
    run:
        (...)
        - {{ pin_compatible('libcxx', min_pin='x.x', max_pin='x.x') }}
`

**Comment by isuruf** [comment]
> I tought backporting the fix in 1.78.0, but from https://github.com/conda-forge/boost-cpp-feedstock/pull/130 it seems that due to ABI breakage we cannot backport stuff to 1.78.0 .

You can rebuild that branch without upgrading the compiler. Then we don't have to worry about ABI breakage.

**Comment by traversaro** [comment]
> > I tought backporting the fix in 1.78.0, but from #130 it seems that due to ABI breakage we cannot backport stuff to 1.78.0 .
> 
> You can rebuild that branch without upgrading the compiler. Then we don't have to worry about ABI breakage.

Thanks, I did not tought of that, https://github.com/conda-forge/boost-cpp-feedstock/pull/135 does that.

**Comment by traversaro** [comment]
Fixed by https://github.com/conda-forge/boost-cpp-feedstock/pull/135, I think that we can close, feel free to re-open if necessary.
