### ISSUE TITLE
Static libraries for boost-cpp

### ISSUE THREAD

**Issue by peter-urban** [conda-forge/boost-cpp-feedstock#141]
### Comment:

Hi,

I am trying to build a conda package for a project that depends on static boost libraries (e.g boost_iostreams.a on linux).

Is it possible to provide these libraries with this package? Or is there another conda package that includes the static libraries?

Best regards
Peter

**Comment by h-vetinari** [comment]
Please continue this discussion in https://github.com/conda-forge/boost-feedstock/issues/159, this feedstock is not in use anymore.
