### ISSUE TITLE
Is there a way to install a boost header only package?

### ISSUE THREAD

**Issue by sandybhat16** [conda-forge/boost-cpp-feedstock#152]
### Comment:

I am trying to install the boost package. But I was wondering if there is a way to specify an option like 'headers_only'. As I only need the header files from this package.
Of course I can install the package and take out the include directory and use. 
But if there was a way to install a header only package, it would be helpful.

**Comment by jschueller** [comment]
no, currently the package provides both includes & libs

**Comment by sandybhat16** [comment]
Thank you for your response.

**Comment by h-vetinari** [comment]
That's not true anymore as of a major overhaul for 1.82 we did. You can install `libboost-headers` and only get the headers

**Comment by jschueller** [comment]
oh, I didnt know that, sorry

**Comment by sandybhat16** [comment]
@h-vetinari is this a package already on conda-forge? I cannot find any with the name '`libboost-headers`'

**Comment by jschueller** [comment]
look again: https://anaconda.org/search?q=libboost-headers

**Comment by h-vetinari** [comment]
> I cannot find any with the name '`libboost-headers`'

If you're looking for the feedstock, it's [here](https://github.com/conda-forge/boost-feedstock). For more context, see #25 / #137 or https://github.com/conda-forge/boost-feedstock/pull/164

**Comment by sandybhat16** [comment]
Thank you @jschueller @h-vetinari . Unfortunately this is only for the version 1.82. For the lower versions like 1.70.0, I might need to create my own recipe. I am new to conda and exploring stuff.

**Comment by h-vetinari** [comment]
Boost has pretty excellent compatibility. If you're only using the headers, I don't see a reason why 1.82 shouldn't work in 99% of the cases. IMO you should give it a try and see if it works. ;-)

**Comment by sandybhat16** [comment]
I am almost sure that it will work. But since our project is already using 1.70.0, we don't want to break the compatibility. Maybe we later update if necessary :)

**Comment by h-vetinari** [comment]
Alright, you do whatever suits you. At least you now have another reason to upgrade. ;)

OTOH, this issue can now be closed.
