### ISSUE TITLE
Creating a libboost-headers only package from existing recipe fails

### ISSUE THREAD

**Issue by sandybhat16** [conda-forge/boost-cpp-feedstock#154]
### Comment:

I am aware of the libboost-headers available for 1.82.0. However I need the libboost-headers for 1.70.0 and hence trying to build a package from the existing recipe at boost-cpp-feedstock. I have downloaded the boost-cpp-feedstock repo and modified the meta.yml and install-lib.bat. However I run into errors while creating a package. Below is the recipe:

meta.yml:

```
{% set version = "1.70.0" %}

{% set boost_libs = [
    "atomic", "chrono", "container", "context", "contract", "coroutine",
    "date_time", "filesystem", "graph", "iostreams", "locale", "log", "log_setup",
    "math_c99", "math_c99f", "math_tr1", "math_tr1f", "prg_exec_monitor",
    "program_options", "random", "regex", "serialization", "system", "thread",
    "timer", "type_erasure", "unit_test_framework", "wave", "wserialization"
] %}
{% set boost_libs = boost_libs + ["math_c99l", "math_tr1l"] %}  # [not ppc64le]
{% set boost_libs_static_only = ["exception", "test_exec_monitor"] %}
{% set boost_libs_py = ["python%s" % py, "numpy%s" % py] %}

package:
  name: boost-split
  version: {{ version }}

source:
  url: https://boostorg.jfrog.io/artifactory/main/release/{{ version }}/source/boost_{{ version|replace(".", "_") }}.tar.bz2
  sha256: 430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778

outputs:
  - name: libboost-headers
    script: install-lib.bat  # [win]

```

install-lib.bat

```
@echo on

if [%PKG_NAME%] == [libboost-headers] (
    REM for libboost-headers, only the headers
    robocopy temp_prefix\include %LIBRARY_INC% /E >nul
    REM robocopy leaves non-zero exit status as sign of success; clear it
    echo "robocopy done"
) else (
    REM everything else
    xcopy /E /Y temp_prefix\lib %LIBRARY_LIB%
)
```

Error attached.
[error.txt](https://github.com/conda-forge/boost-cpp-feedstock/files/13043616/error.txt)

**Comment by h-vetinari** [comment]
This is not our business to support. You have 1.82 available, and the headers are compatible, so just use 1.82 (really don't understand what's holding you at 1.70 if you only want the headers).

If you're 100% convinced that this is what you need to do, you'll have better chances of success by using the recipe from the boost (not boost-cpp) feedstock and downgrading the version from 1.82 ->1.70.

**Comment by h-vetinari** [comment]
> by using the recipe from the boost (not boost-cpp) feedstock and downgrading the version from 1.82 ->1.70.

I see now that this is what you've done already (even though you raised the issue on another feedstock...). You're on your own there. The boost recipe should have enough context for you to debug what's happening. I doubt it's a good use of your time, but if that's what you want to do...
