### ISSUE TITLE
Also provide `libboost...-mt` libraries?

### ISSUE THREAD

**Issue by grisaitis** [conda-forge/boost-cpp-feedstock#18]
Hi! I'm on a Mac and need `libboost_thread-mt.[a,dylib]`, but this package does not supply it. It only provides `libboost_thread.[a,dylib]`. Could this feedstock / build procedure be modified to include those libraries? I think it's as simple as adding symlinks: `libboost_thread-mt` to `libboost_thread`.

My situation: I'm building [caffe](https://github.com/BVLC/caffe) from source. I got an error from make saying `ld: library not found for -lboost_thread-mt`, same as [this person on SO](https://stackoverflow.com/questions/34589573/error-installing-caffe). It seems like most people use brew to install boost on OS X, and brew includes the `-mt` `libboost` libraries. But I wanted to use conda to avoid the OS-level install. 

Referencing https://github.com/conda-forge/boost-feedstock/issues/48

**Comment by jakirkham** [comment]
We will want to do this will all of the libraries. This can likely be done with a `find ... | xargs ... ln -s ...` type command. Also should update the Unix tests to check for these.

**Comment by grisaitis** [comment]
Thanks, John - updated the title accordingly. I thought `boost_thread` was the only library with a `mt` flavor.

**Comment by shivareddyiirs** [comment]
Any progress or solution for problem where boost...- mt is required by CMAKE

**Comment by jakirkham** [comment]
@shivareddyiirs, would read issue ( https://github.com/conda-forge/boost-feedstock/issues/48 ). As is explained there, we already build the `*-mt` variant libraries, but the suffix is not included in the name. So one may need adjust their linking flags to pick those up.

**Comment by h-vetinari** [comment]
Closing this issue as solved, see the last comment as well as https://github.com/conda-forge/boost-feedstock/issues/48
