### ISSUE TITLE
linker error on static lib usage with new lib name scheme

### ISSUE THREAD

**Issue by argltuc** [conda-forge/boost-cpp-feedstock#32]
Issue:
Building a package via cmake which use boost with static libs issue a linker error like `LINK : fatal error LNK1104: cannot open file 'boost_system.lib'`, while the Linker section of VS project file reference `"C:\Users\argl\Documents\coding\minimal_boost\builds\minimal-boost_1531237067460\_h_env\Library\lib\libboost_system.lib"`
This issue seems to come up since boost package version 1.66 build 1 (since the new name scheme for boost libs was introduced).

You will find a minimal package example attached.

To clearify, my bld.bat called cmake like following:
```
cmake .. -G "Visual Studio 14 2015 Win64" ^
	 -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
	 -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
         -DBoost_USE_STATIC_LIBS=ON
```
This results in the linker error mentioned above.

If you will set `DBoost_USE_STATIC_LIBS` to `OFF` all is fine, but to use dynamic libs is not my use case.

<br/>
Environment (conda build output):
<details>

```
The following NEW packages will be INSTALLED:

    blas:           1.1-openblas                  conda-forge
    boost:          1.67.0-py36_vc14_0            conda-forge [vc14         ]
    boost-cpp:      1.67.0-vc14_0                 conda-forge [vc14         ]
    certifi:        2018.4.16-py36_0              conda-forge
    cmake:          3.11.4-0                      conda-forge
    icc_rt:         2017.0.4-h97af966_0
    intel-openmp:   2018.0.3-0
    libflang:       5.0.0-vc14_20180208           conda-forge [vc14         ]
    llvm-meta:      5.0.0-0                       conda-forge
    mkl:            2018.0.3-1
    mkl_fft:        1.0.2-py36_0                  conda-forge
    mkl_random:     1.0.1-py36_0                  conda-forge
    numpy:          1.14.3-py36_blas_openblas_200 conda-forge [blas_openblas]
    numpy-base:     1.14.3-py36h5c71026_0
    openblas:       0.2.20-vc14_8                 conda-forge [vc14         ]
    openmp:         5.0.0-vc14_1                  conda-forge [vc14         ]
    pip:            9.0.3-py36_0                  conda-forge
    python:         3.6.5-1                       conda-forge
    setuptools:     40.0.0-py36_0                 conda-forge
    vc:             14-0                          conda-forge
    vs2015_runtime: 14.0.25420-0                  conda-forge
    wheel:          0.31.1-py36_0                 conda-forge
    wincertstore:   0.2-py36_1                    conda-forge
    zlib:           1.2.11-vc14_0                 conda-forge [vc14         ]

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
System: windows 10 64bit
Compiler: Visual Studio 2015 / VC14 
```
$ conda info
active environment : None
       user config file : C:\Users\argl\.condarc
 populated config files : C:\Users\argl\tools\dev\Miniconda3\.condarc
          conda version : 4.5.7
    conda-build version : 3.10.9
         python version : 3.5.5.final.0
       base environment : C:\Users\argl\tools\dev\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\argl\tools\dev\Miniconda3\pkgs
                          C:\Users\argl\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\argl\tools\dev\Miniconda3\envs
                          C:\Users\argl\AppData\Local\conda\conda\envs
                          C:\Users\argl\.conda\envs
               platform : win-64
             user-agent : conda/4.5.7 requests/2.19.1 CPython/3.5.5 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

[minimal_boost.zip](https://github.com/conda-forge/boost-cpp-feedstock/files/2181167/minimal_boost.zip)

**Comment by jschueller** [comment]
does this happen with 1.67 ?

**Comment by isuruf** [comment]
Can you try doing `set "CXXFLAGS=/DBOOST_AUTO_LINK_NOMANGLE" before the cmake invocation? You'll have to clean the build dir and rebuild after making the above change.

**Comment by isuruf** [comment]
It should be `set "CXXFLAGS=/DBOOST_ALL_NO_LIB"`

**Comment by isuruf** [comment]
Alternatively, can you try changing line https://github.com/boostorg/config/blob/boost-1.67.0/include/boost/config/auto_link.hpp#L410 to 
```
# pragma comment(lib, BOOST_LIB_PREFIX BOOST_STRINGIZE(BOOST_LIB_NAME) ".lib")
```

**Comment by argltuc** [comment]
Well done, `set "CXXFLAGS=/DBOOST_ALL_NO_LIB"` solves the problem!
Thanks for your fast answer!

**Comment by argltuc** [comment]
Okay, I just tested the second way with `# pragma comment(lib, BOOST_LIB_PREFIX BOOST_STRINGIZE(BOOST_LIB_NAME) ".lib")` which works also quite fine.

Maybe it would a good idea to patch this file in the package, that the user just can call `-DBoost_USE_STATIC_LIBS=ON` and all works fine?

**Comment by isuruf** [comment]
https://github.com/conda-forge/boost-cpp-feedstock/pull/33

**Comment by argltuc** [comment]
@isuruf I just tried out your PR, create a boost-cpp package which I used to build my specific projects and currently it looks good and work like a charm :)

**Comment by argltuc** [comment]
Okay, it seems we have to go one step back.
I just tried the potential new package with my minimal project and the setting `-DBoost_USE_STATIC_LIBS=OFF`. This was with the latest package not a problem. but now with the PR dynamic lib usage looks for `libboost_system.lib` and not for the needed `boost_system.lib`. So the failure is vice versa from the original issue.

**Comment by jschueller** [comment]
we removed static libs
