### ISSUE TITLE
Dependency hell from three ABI changes per year

### ISSUE THREAD

**Issue by epruesse** [conda-forge/boost-cpp-feedstock#35]
BOOST releases a new minor version about three times each year. Each version brings a new ABI and is not compatible with older releases.

In the current scheme, that means that packages linking against `libboost*` can only be installed into the same environment if they were built no more than 4 months apart!

There are a few options out of this dilemma:
1) Don't build the DLL at all, force everything to link statically
2) Trigger a CI rebuild of all dependent packages as soon as BOOST is updated to a new minor version.
2a) Limit updates to 1 per year, skipping boost versions.
3) Build `libboostX.Y` packages using `outputs:` and use CB3 to push it into the run dependencies if `libboost-dev` is used in the host dependencies. 

I'd prefer 3 as it allows co-installing software long term without constant rebuilds, but benefits from DLL space savings and updating.

Incidentally - it might be worthwhile to also build individual packages for each boost library. Or at least split out the larger ones. The whole thing is quite larger, after all.

**Comment by jschueller** [comment]
we use shared libs, with boost currently pinned to 1.67 (using cb3):
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L292
