### ISSUE TITLE
macOS crashes with 1.69.0 when using conda packages on Xcode >= 7

### ISSUE THREAD

**Issue by wesm** [conda-forge/boost-cpp-feedstock#40]
We've been having users report crashes with the boost-cpp=1.69.0 macOS packages on newer Xcode

https://travis-ci.org/wesm/arrow/jobs/469297420#L2856

**Comment by wesm** [comment]
Note: these crashes aren't present in Xcode 6.4

**Comment by wesm** [comment]
Apologies, it seems the problem is present on older versions of boost-cpp

https://travis-ci.org/wesm/arrow/jobs/469307447#L1809

I'll do some searching to see if it's a known issue

**Comment by jakirkham** [comment]
It does look like 1.69.0 is installed, but it’s also detecting 1.67.0. Not entirely sure what is going on, but if it’s mixing two different Boost installs that could cause this problem. Is it possible it’s picking Boost up from Homebrew or elsewhere?

**Comment by wesm** [comment]
That's a different issue. I think @jakirkham was talking about

https://travis-ci.org/wesm/arrow/jobs/469307447#L852

I'm not sure why it is loading the dylibs from /usr/local/lib because we prepended the conda lib path to LD_LIBRARY_PATH. 

In the failures I linked above Boost is being statically linked so this /usr/local/lib issue isn't relevant

**Comment by isuruf** [comment]
Can you show me the exact line of the failure you are talking about?

**Comment by wesm** [comment]
Yes, this segmentation fault:

https://travis-ci.org/apache/arrow/jobs/469666491#L2203

Two other developers have confirmed the problem with 1.69.0 locally but that 1.68.0 works as expected:

* @kszucs  https://issues.apache.org/jira/browse/ARROW-4050?focusedCommentId=16724164&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16724164
* @tanyaschlusser https://issues.apache.org/jira/browse/ARROW-4050?focusedCommentId=16723180&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16723180

**Comment by jschueller** [comment]
1.69 is not the current version anymore
