### ISSUE TITLE
boost 1.70: Boost_INCLUDE_DIR not set

### ISSUE THREAD

**Issue by looooo** [conda-forge/boost-cpp-feedstock#48]
I see this issue for win, osx, linux:
https://github.com/conda-forge/smesh-feedstock/pull/24

The called commands are located here:
https://github.com/LaughlinResearch/SMESH/blob/master/CMakeLists.txt#L74L97

**Comment by jschueller** [comment]
it's probably due to boost providing its own cmake config now using target properties, I think includes are not needed anymore

**Comment by jschueller** [comment]
try pass -DBoost_INCLUDE_DIRS=1

**Comment by xhochy** [comment]
You can workaround this using `-DBoost_NO_BOOST_CMAKE=ON`.

**Comment by looooo** [comment]
thanks @jschueller and @xhochy ! `-DBoost_NO_BOOST_CMAKE=ON` works.
