### ISSUE TITLE
boost-cpp 1.70 is making conda solve 70x slower

### ISSUE THREAD

**Issue by tadeu** [conda-forge/boost-cpp-feedstock#49]
I think that the problem is related to this: `conda` solver is unable to prune versions, because it won't find a satisfiable `boost-cpp` version.

Things needed to reproduce the problem are here:

https://gist.github.com/tadeu/49c6de435dae6764f6616eb10efde2a4

(this could also be a `conda` problem, instead of a particular problem in `boost-cpp`)

The diff for `conda env update --debug`, with both Boost versions, is here:

https://gist.github.com/tadeu/49c6de435dae6764f6616eb10efde2a4/revisions#diff-8c6e71389c61ffe86203031a361d8c00

Note that around line 563, it prunes all `boost-cpp` down to `0`

```
DEBUG conda.resolve:filter_group(400): boost: pruned from 122 -> 1
DEBUG conda.resolve:filter_group(400): boost-cpp: pruned from 39 -> 0
```

**Comment by xhochy** [comment]
In this case, do you have libboost installed?

**Comment by tadeu** [comment]
Sorry, I've updated the issue description and added a comment in the PR, I've just realized that there is this `libboost` package in Anaconda main, so it seems unrelated.

**Comment by xhochy** [comment]
We're also in the middle of a migration of the boost-cpp pinning from 1.68 to 1.70. Maybe not all your dependencies were already updated: https://conda-forge.org/status/

**Comment by tadeu** [comment]
I'm using an `environment.yml` with everything pinned down (with `==`), so it would fail if some dependency was not updated already.  We use some mirrors and some custom channels here, but I'll try to craft an `environment.yml` that reproduces the problem with only Anaconda and conda-forge.

**Comment by tadeu** [comment]
Here is an `environment.yml`: https://gist.github.com/tadeu/49c6de435dae6764f6616eb10efde2a4/revisions

The command used is `conda env update --file environment-boost-1.68.yml --prune` (or `conda env update --file environment-boost-1.70.yml --prune`). With `boost-cpp ==1.68.0` it's taking 10s to solve, with `boost-cpp ==1.70.0` it's taking _a lot of time_ (more than 2 minutes and counting).

**Comment by tadeu** [comment]
Just FYI, I've solved the issue locally by adding `boost-cpp` packages to a higher priority internal channel, with higher build numbers and removing this from `index.json`:

```
  "constrains": [
    "libboost <0"
  ],
```

but I understand that this is not a solution for everyone, in our case we don't have `libboost` in our Anaconda `main` mirror because we filter some packages out.

**Comment by msarahan** [comment]
I think we should be able to sort something out here.  I'll see what we can do.  This seems like a solver bug, or at least a non-optimal handling of the situation.

**Comment by tadeu** [comment]
Note: I've tested the same `conda env update` with conda 4.7.3 from conda-canary, and it's down to 5.5 minutes (from the old 11 minutes), but it's still much slower than for Boost 1.68 packages.

**Comment by jschueller** [comment]
can you retry with latest packages and check that is stll a valid issue ?

**Comment by jakirkham** [comment]
Given this issue is a few years old, several versions of Boost have come out, the original use cases involves mixing `conda-forge` & `defaults` (which is no longer supported), and possibly other changes I've missed, going to close this out. If this is still coming up, would recommend starting a new issue with a reproducer. Thanks!
