### ISSUE TITLE
--with-libraries=graph,filesystem add

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/boost-cpp-feedstock#5]
@mictadlo commented on [Sun Jan 22 2017](https://github.com/conda-forge/boost-feedstock/issues/30)

Hi,
Would you be able to add `--with-libraries=graph,filesystem`?

Thank you in advance.

Best wishes,

MIchal

---

@jakirkham commented on [Sun Jan 22 2017](https://github.com/conda-forge/boost-feedstock/issues/30#issuecomment-274379459)

Moving to [boost-cpp]( http://github.com/conda-forge/boost-cpp-feedstock ) as that is where general Boost stuff is handled now. This feedstock tacks on Boost.Python in addition to everything included in that package.

**Comment by jakirkham** [comment]
AFAICT @mictadlo we are building both. Could you please give us some more insight into the issue you are encountering?

**Comment by mictadlo** [comment]
Hi,
I got [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/196466226#L698) the following error:
```
  Could not find the following static Boost libraries:
          boost_graph
  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
```

However, I provider [here](https://github.com/bioconda/bioconda-recipes/pull/3646/commits/eff2cb06b3072fe80732b7e459671ba4c71e78d4#diff-a3ee18dbffa8a5e14f29a360ae6657e9R8) `BOOST_LIBRARYDIR`.

What could I miss?

Thank you in advance,

Michal

**Comment by isuruf** [comment]
You are using boost from the `defaults` channel. We have no control of that. See the readme, https://github.com/conda-forge/boost-cpp-feedstock#installing-boost-cpp

**Comment by mictadlo** [comment]
Thank you. How do I contact the people behind the `defaults` channel?

**Comment by jakirkham** [comment]
Please raise an issue at this [repo]( https://github.com/ContinuumIO/anaconda-recipes ).
