### ISSUE TITLE
boost-cpp 1.70.0 cmake config files give the static libs, not shared

### ISSUE THREAD

**Issue by microe** [conda-forge/boost-cpp-feedstock#61]
Issue: When building software with cmake that depends on boost-cpp 1.70.0, the cmake configs in $CONDA_PREFIX/lib/cmake give the static version of the boost libraries instead of the shared libraries.

This will likely break the build for various reasons, for example libboost_filesystem.a has hidden symbols in it. As soon as you try to link with a shared object file, the build will error out because hidden objects/symbols cannot be used in shared object builds.

Setting the cmake variable Boost_USE_STATIC_LIBS to "OFF" causes cmake to error out because it can't find libboost_system.so.

If you instead move the cmake config files away, then FindBoost.cmake can conclude and works properly.

For example:
```
$ mkdir /tmp/hold-cmake-config
$ mv $CONDA_PREFIX/lib/cmake/?oost* /tmp/hold-cmake-config/
```

Now cmake and FindBoost.cmake can do their thing and the build finishes.

**Comment by isuruf** [comment]
Can you send a PR to rename the cmake file folder to something like `$CONDA_PREFIX/lib/cmake-bak/` ?

**Comment by jschueller** [comment]
Cant we just disable static libs ?

**Comment by microe** [comment]
Is it OK to just move the boost files? The $PREFIX/lib/cmake directory might have other

**Comment by jakirkham** [comment]
Did you mean to close this @microe?

**Comment by microe** [comment]
No, miss hit in my browser. Sorry.

**Comment by microe** [comment]
Hopefully the submitted PR works out. If it doesn't, I'll try just moving the boost cmake config files instead of the whole directory.

**Comment by timsnyder** [comment]
The logic in the 1.70 boost cmake files is defintely busted.  I danced around it in my project by doing [this](https://github.com/sparcians/map/commit/bce2d8376f92ffb31902af25e0e6e1e5e00d9ef0)

**Comment by bretttully** [comment]
@timsnyder Thanks!

**Comment by jschueller** [comment]
we just removed static libs

**Comment by microe** [comment]
Yay!
