### ISSUE TITLE
make a boost-cpp 1.72 branch

### ISSUE THREAD

**Issue by beckermr** [conda-forge/boost-cpp-feedstock#72]
It appears that one of our migrations got ahead of another and we need a 1.72 branch on the latest icu version. ping @conda-forge/boost-cpp

**Comment by isuruf** [comment]
Feel free to send a PR to downgrade the version and I'll merge to a new branch when tests pass.

**Comment by CJ-Wright** [comment]
also xref: https://github.com/conda-forge/cfep/pull/32

**Comment by beckermr** [comment]
yup!
