### ISSUE TITLE
System layout for windows

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/boost-cpp-feedstock#8]
@isuruf commented on [Wed Jan 04 2017](https://github.com/conda-forge/boost-feedstock/issues/25)

Since conda has vc features, it's fine to have system layout instead of appending the compiler version in the dll names.

(One advantage would be that cmake's FindBoost.cmake script will be able to find newer boost libraries without requiring patches like, conda-forge/cmake-feedstock#29)

---

@jakirkham commented on [Sun Jan 22 2017](https://github.com/conda-forge/boost-feedstock/issues/25#issuecomment-274379575)

Should this be moved to [boost-cpp]( http://github.com/conda-forge/boost-cpp-feedstock )?

---

@isuruf commented on [Sun Jan 22 2017](https://github.com/conda-forge/boost-feedstock/issues/25#issuecomment-274388513)

Yes.

**Comment by jschueller** [comment]
why close ?

**Comment by isuruf** [comment]
I don't think this will work out with the auto-linking thing. We'll have to add `-DBOOST_ALL_NO_LIB` to all recipes or in the feedstock. One reason for this feature was to make things easier, but I think it's going to make things harder
