### ISSUE TITLE
package variant without header files?

### ISSUE THREAD

**Issue by Anthchirp** [conda-forge/boost-cpp-feedstock#83]
I am wondering whether there could be a boost-cpp package variant that only contains the binary library files and leaves out the header files. [The use case for this would be a downstream binary package linking to boost libraries contained in this package.](https://github.com/conda-forge/staged-recipes/pull/10021)

A `boost-cpp` package without the header files would currently leave out some 13000 files, making for a much faster installation, and reduce the package size by about 75%.

I do not consider myself a C++ developer, so if I fundamentally misunderstood how boost-cpp is intended to work then please correct me 🙂

**Comment by xhochy** [comment]
We should separate the package into multiple outputs. Then one should select the necessary parts of boost instead of all of it when building.

**Comment by hmaarrfk** [comment]
I guess the challenge is that listing the files that each split package is to include with conda requires manaully listing (or at least it did when i last looked at it).

It was impossible to say that `everything in the include folder should go in one package`.

That makes it really hard to maintain.

When i've needed to reduce the install size of my application, i simply removed the whole include directory in a post install script (along with all the `.a` files in the `lib` directory).

**Comment by hmaarrfk** [comment]
This change should be done in sync with:
https://github.com/AnacondaRecipes/boost-cpp-feedstock/tree/master/recipe

**Comment by jakirkham** [comment]
The way to do this would be to use install scripts for each component. These could install full directories at once. That said, there will also be libraries, docs, and possibly other things. So really what one would want to do is configure Boost to just install that component. Idk how well this strategy would work with Boost (maybe someone else here does), but that is something other split packages use successfully

**Comment by h-vetinari** [comment]
This has been done in https://github.com/conda-forge/boost-feedstock/pull/164, closing

**Comment by hmaarrfk** [comment]
congrats!!!! amazing work!
